<a href="https://colab.research.google.com/github/sheikhsaifalislam/100DaysOfMachineLearning/blob/main/Day01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

Python is used for multiple purposes, and at most of the time we might deal with complex mathematics formulas and equations. In order to save time in hard coding all those Mathematical equations Python provides Numpy module. Numpy stands for Numerical Python Library, and this is widely used in implementing Neural Networks and in those algorithms where complex mathematics is required.

## **Benefits of using Numpy:**


*   An array object of arbitrary homogeneous items.

*   Fast mathematical operations over arrays.
*   Linear Algebra, Fourier Transforms, Random Number Generation.


*   Vectorization and Broadcasting which helps to get rid of explicit for loop.



# **Install Numpy**

```
pip install numpy
```
If you get no error, then numpy is successfully installed. If you get ModuleNotFoundError then it means that numpy was not installed.



In [1]:
import numpy as np

# **Generating Array Using Numpy**

In [6]:
arr_ran = np.arange(0,10)
arr_ran

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
type(arr_ran)

numpy.ndarray

# **Size Of An Array**
Size attribute is used to display the total length of the Numpy array. Don’t confuse it with length, eventhough they both does the same task the results are different, here is the proof.

In [9]:
arr = np.array(range(1,10))
print("Length:", len(arr))
print("Size:",arr.size)

Length: 9
Size: 9


That is really weird, I did say prints different result, but here we are getting same result.

In [10]:
arr = np.array([range(1,10)])
print("Length:", len(arr))
print("Size:",arr.size)

Length: 1
Size: 9


What just happened here? Here we are dealing with dimensions. When we have single dimensional array, i.e., example-1. In example 1, the array was in single dimension and thus both len() and size executed the same result. But in example 2, the main hero is 2 dimension array, and len() executes 1, because it is used to deal with just 1D Array. And size is used to deal with multiple dimension. And that is the reason why we use size attribute to execute the total elements in the given array.

# **Memory Bytes Of An Array**


```
itemsize 
```
gives the memory size of one element of NumPy array in bytes.


In [11]:
arr = np.arange(10)
arr.size*arr.itemsize

80

# Method 2 

```
nbytes 
```   
calculates the total bytes used by the elements of the NumPy array.



In [12]:
arr.nbytes

80

# **N-Dimensional Arrays**
N-Dimensional Arrays means Multiple Dimensional Arrays. Where N is integer value starts from 2 and ends to N(infinity value).

In [13]:
arr_2D = np.array([[1,2,3,4],[5,6,7,8]])
arr_2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr_2D.ndim

2

In [15]:
arr_2D.size

8

To check the dimension of the numpy array we use 

```
ndim
```
attribute.



# Shape And Reshape An Array
On introducing to N-dimensional array, we have come across to only size and dimension of the array. But in what matrix order is it in? The word Matrix is nothing but the collection of elements arranged in rows and columns. Furthermore, this Matrix is off different types

```
Unit Matrix(np.ones), Zero Matrix(np.zeros), Square Matrix, Identity Matrix
```
and many more. All matrix are different but order. An order is usually written as (row x column), to be more precise 

```
(mxn)
```
 Where m is the total number of rows and n is the total number of columns.

Shape returns in Tuple i.e., (m,n) for two dimensional array, (m,n,o) for three dimensional array.
m,n,o all are numeric value. For example: (1,2,3) or (1,2) or (2,)




In [16]:
n_arr = np.random.rand(10)
n_arr

array([0.93083671, 0.92030361, 0.20177086, 0.02780393, 0.76727908,
       0.38055481, 0.37002215, 0.13609325, 0.61900517, 0.75574268])

In [17]:
n_arr.shape

(10,)

In [18]:
n_arr.ndim

1

Now lets reshape this array

In [19]:
n_arr = n_arr.reshape(2,5)

In [20]:
n_arr

array([[0.93083671, 0.92030361, 0.20177086, 0.02780393, 0.76727908],
       [0.38055481, 0.37002215, 0.13609325, 0.61900517, 0.75574268]])

In [21]:
n_arr.shape

(2, 5)

In [22]:
n_arr.ndim

2

As you can notice we now have a two dimension array instead of 1D array

**Note**: Always remember, since shape returns in tuple len(arr.shape) == arr.ndim. The length of the shape denotes the dimension of the given array. Thus len(arr.shape)== arr.ndim will return true.

In [23]:
len(n_arr.shape)

2

In [24]:
len(n_arr.shape) == n_arr.ndim

True

# This is how three dimensional array looks like.

In [27]:
arr_3D = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [28]:
arr_3D

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [29]:
arr_3D.ndim

3

In [30]:
arr_3D.shape

(1, 3, 3)

**How to create a Random Array?**

Creating an array filled with random numbers is the most essential operation in Numpy. Sometimes when you need large size of data with bigger dimensions we commonly prefer the array with random values.

In [32]:
ran_arr = np.random.random(10)

In [33]:
ran_arr

array([0.53995264, 0.8669453 , 0.20654616, 0.42641873, 0.28083585,
       0.97002954, 0.41353012, 0.1403627 , 0.71240641, 0.47086128])

In [34]:
ran_arr = np.random.rand(5)

In [35]:
ran_arr

array([0.74871966, 0.36904451, 0.69017811, 0.00980092, 0.96158138])

In [36]:
ran_arr = np.random.randn(5)

In [37]:
ran_arr

array([ 0.30587871, -1.00041286, -0.1213975 ,  0.59071486,  0.67102314])

# Difference Between random.rand() vs random.random()

In [38]:
random_20_arr = np.random.random(20,3)

TypeError: ignored

In [39]:
random_20_arr= np.random.rand(20,3)

In [40]:
random_20_arr

array([[0.94180784, 0.90944684, 0.72121886],
       [0.78381527, 0.54672684, 0.31194149],
       [0.62303614, 0.86637082, 0.40997036],
       [0.23603832, 0.09197387, 0.29134287],
       [0.87299404, 0.9823594 , 0.81677756],
       [0.871663  , 0.49779858, 0.64981219],
       [0.75428855, 0.53370696, 0.43589701],
       [0.25717752, 0.7742462 , 0.91783253],
       [0.38745494, 0.12017038, 0.8012845 ],
       [0.03897079, 0.00891191, 0.19304572],
       [0.31046381, 0.87547036, 0.82395898],
       [0.55024535, 0.67918861, 0.21216221],
       [0.23292982, 0.79190593, 0.54827428],
       [0.26965507, 0.33894971, 0.5130991 ],
       [0.68317511, 0.68264556, 0.17313326],
       [0.64351131, 0.53459624, 0.67487722],
       [0.91974012, 0.20033867, 0.39440791],
       [0.07067283, 0.49126866, 0.76776172],
       [0.26128455, 0.84112142, 0.91997849],
       [0.19816726, 0.32350642, 0.22645949]])

**np.random.random is used to return random numbers of only 1D array whereas np.random.rand works on any dimension:** ⏰

# Indexing And Slicing Of Numpy Array
Indexing is the method to find the element at the specific location i.e., index

In [45]:
index = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [46]:
index

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
index.shape #3rows 4 columns

(3, 4)

In [48]:
index[0][0] #returns the first index from the first row

1

In [49]:
index[0]        #returns first row

array([1, 2, 3, 4])

In [50]:
index[-1]

array([ 9, 10, 11, 12])

Slicing is the method that is used to select the specific sequence of elements from the array

Syntax to slice: array[row_start:row_end,column_start:column_end]

In [51]:
slice = index

In [52]:
slice

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
slice[0:2] #to select first 2 rows

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
slice[1:2, 0:2]   #2nd row[5,6,7,8] and 0 to 1 column[5,6]

array([[5, 6]])

In [55]:
slice[[0,-1]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [56]:
slice[0:,-1] #last column

array([ 4,  8, 12])

Using step size i.e., the third slice index:

Syntax to slice_range: array[row_start:row_end:row_step,column_start:column_end:column_step]

In [57]:
slice[0::2,-1:]  #check the last column and select alternative postion

array([[ 4],
       [12]])

In [58]:
slice[0:3:2,0:-1:2]

array([[ 1,  3],
       [ 9, 11]])

In [59]:
slice

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# **Transpose Of The Array**
Transpose of the matrix is the interchange of row and column elements. Transpose of the matrix also effects the shape of an array. For instance if the original array as 3 rows and 2 columns then the transpose of the matrix will have 2 rows and 3 columns.

Syntax: arr.T

In [60]:
two_dim_arr = np.array([[10,20,30,40],[50,60,70,80]])
two_dim_arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [61]:
two_dim_arr.shape

(2, 4)

In [62]:
two_dim_arr.T

array([[10, 50],
       [20, 60],
       [30, 70],
       [40, 80]])

In [63]:
two_dim_arr.T.shape

(4, 2)

The matrix order of original array is (2,4), as per the definition of Transpose Matrix, the transpose shape will be (4,2).

**Mean, Media, Variance and Standard Deviation**

Mean, Median, Variance and Standard Deviation, these concepts are considered to be types of Descriptive Statistics. Statistics? Yes it brings back the school days. There are two types of descriptive statistics, measures of central tendency and measures of spread. The mean, median and mode are all measures of central tendency, while the variance and standard deviation are measures of spread. Let us look into individual definitions.

In [64]:
marks = [65,78,94,66,88,80,91]
marks = np.array(marks)
marks

array([65, 78, 94, 66, 88, 80, 91])

**Mean**

Mean is used to calculate the arithmetic average of the given data. It would only be used on quantitative data.

In [65]:
mean = np.mean(marks)
mean

80.28571428571429

In [66]:
alternative_mean = sum(marks)/len(marks)
alternative_mean

80.28571428571429

**Median**

The median is the middle number in a sorted, ascending or descending, list of numbers and can be more descriptive of that data set than the average.

In [67]:
median = np.median(marks)

In [68]:
median

80.0

In [69]:
marks.sort()
alternative_median = marks[len(marks)//2]
print(alternative_median)

80


**Variance**

Variance is the sum of squares of differences between all numbers and means. It also defined as the average of the squares of the differences between the individual (observed) and the expected value.

In [70]:
variance = np.var(marks)
variance

115.06122448979592

In [71]:
sum = 0
for i in marks:
    sum += (i-marks.sum()/len(marks))**2

alternative_variance = sum/len(marks)
print("%.4f"%alternative_variance)

115.0612


**Standard Deviation**

It is a measure of the extent to which data varies from the mean.

In [72]:
std_deviation = np.std(marks)
print(std_deviation)

10.726659521481789


In [73]:
alternative_std = np.sqrt(alternative_variance)
print("%.4f"%alternative_std)

10.7267


**What Is Linspace?**

Linspace divides a sequence evenly between start and end based on the step value.

In [74]:
distibution = np.linspace(0,100,5)
distibution

array([  0.,  25.,  50.,  75., 100.])

In [75]:
distibution = np.linspace(0,100,2)
distibution

array([  0., 100.])

There are 3 important NumPy method to be familiarize with: 
1. Sum of Numpy Array
2. Matrix Multiplication or Dot Product
3. Exponential and Logarithms

# Sum of Array: Both Vertical and Horizontal

In [76]:
sum_arr_eg = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])

In [77]:
sum_arr_eg

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [78]:
sum_arr_eg.sum()  #calculates the entire sum

30

In [79]:
sum_arr_eg.sum(axis=0) #0 goes downwards 

array([10, 10, 10])

In [80]:
sum_arr_eg.sum(axis=1) #1 goes sidewards

array([ 3,  6,  9, 12])

**Matrix Multiplication And Dot Product**

In [81]:
w = np.random.rand(2,3) #mxn = 2x3
x = np.random.rand(3,1) #mxn = 3x1
#matrix mul = 2x3,3x1 = 2,1
#lets see the dimension

In [82]:
w

array([[0.66641083, 0.99333269, 0.87783189],
       [0.74723326, 0.89567861, 0.9795709 ]])

In [83]:
x

array([[0.70388223],
       [0.86764101],
       [0.24878351]])

In [84]:
matrix_mul = np.matmul(w,x)
matrix_mul

array([[1.54932102],
       [1.54679279]])

In [85]:
matrix_mul.shape

(2, 1)

In [86]:
dot_product = np.dot(w,x)
dot_product

array([[1.54932102],
       [1.54679279]])

# Exponential And Logarithms

In [87]:
np.exp(2)

7.38905609893065

In [88]:
y = 1.4
m = 3
c = 0.4
z = y*m + c
sigmoid = 1/(1+np.exp(-z))
sigmoid

0.9900481981330957

In [89]:
np.log(10)

2.302585092994046

In [90]:
np.log2(10)

3.321928094887362

In [91]:
np.log2(2)

1.0

In [92]:
np.log10(10)

1.0

In [93]:
np.log10(50)

1.6989700043360187